---
default:
  v_bitrate: 4992
  a_bitrate: 128
  x264:
    qcomp: '0.9'
    rc-lookahead: 60
    keyint: 720
    me: umh
    merange: 48
    subme: 10
    ref: 4
    b-pyramid: none
    b-adapt: 2
    bframes: 3
    trellis: 2
    psy-rd: 1.0,1.0
    dct-decimate: 0
    deblock: '0,0'
  nvenc:
    qcomp: '0.9'
    rc-lookahead: 60
    g: 720
    me_method: umh
    me_range: 48
    subq: 10
    refs: 4
    b_adapt: true
    bf: 3
    trellis: 2
  analyse: {}
  smooth:
    rate:
      num: 60
      den: 1
      abs: true

hq: &hq
  v_bitrate: 7552

anime: &anime
  x264:
    ref: 8
    bframes: 5
    psy-rd: 0.4,0.0
    aq-strength: '0.6'
    deblock: '1,1'
  nvenc:
    refs: 8
    bf: 5
  analyse:
    block:
      w: 8
      overlap: 3
    refine:
    - thsad: 1000
  smooth:
    algo: 2

anime-hq:
  <<: *hq
  <<: *anime
